In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
arr = np.array([1,2,3,4,5], np.int8)

In [5]:
arr

array([1, 2, 3, 4, 5], dtype=int8)

In [6]:
arr[0]

1

In [7]:
arr1 = np.array([[1,2,3,4,5]], np.int8)

In [8]:
arr1

array([[1, 2, 3, 4, 5]], dtype=int8)

In [9]:
arr1[0,2]

3

In [10]:
arr.dtype

dtype('int8')

In [11]:
arr.size

5

In [12]:
arr.shape

(5,)

In [13]:
arr1.shape

(1, 5)

In [14]:
arr1[0,3] = 52

In [15]:
arr1

array([[ 1,  2,  3, 52,  5]], dtype=int8)

In [16]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [17]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
listarray.dtype

dtype('int32')

In [19]:
listarray.shape

(3, 3)

In [20]:
listarray.size

9

In [21]:
np.array({34,56,78})

array({56, 34, 78}, dtype=object)

In [25]:
zeros = np.zeros((2, 5))

In [26]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
linspace = np.linspace(1,5,4)

In [29]:
linspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [30]:
emp = np.empty((4,6))

In [31]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        7.56597091e-307, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.24610383e-306,
        6.89804132e-307, 1.11261162e-306, 8.34443015e-308]])

In [39]:
emp_like = np.empty_like(listarray)

In [40]:
emp_like

array([[          0,           0, -1924695088],
       [        552, -1924693104,         552],
       [-1924692976,         552,           0]])

In [41]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
ide = np.identity(4)

In [43]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [44]:
arr2 = np.arange(99)

In [45]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [46]:
arr2 = arr2.reshape(3,33)

In [47]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [48]:
arr2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [49]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
listarray.sum(axis=0)

array([12, 15, 18])

In [51]:
listarray.sum(axis=1)

array([ 6, 15, 24])

In [52]:
# transpose matrix
listarray.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
# iterating the array using flat
listarray.flat

In [54]:
for i in listarray.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [55]:
arr.ndim

1

In [56]:
listarray.ndim

2

In [57]:
arr.nbytes

5

In [58]:
listarray.nbytes

36

In [59]:
one = np.array([2,45,67,345,78])

In [60]:
one.argmax()

3

In [61]:
one.argmin()

0

In [68]:
one.argsort()

array([0, 1, 2, 4, 3], dtype=int64)

In [62]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
listarray.argmax()

8

In [64]:
listarray.argmin()

0

In [66]:
listarray.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [67]:
listarray.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [70]:
ar = np.array([[1,2,3],[4,5,6],[7,1,0]])
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [71]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [72]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [74]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [75]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [76]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [77]:
ar2 = np.array([[4,5,6],[0,12,3],[9,0,1]])

In [80]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [78]:
ar2

array([[ 4,  5,  6],
       [ 0, 12,  3],
       [ 9,  0,  1]])

In [79]:
ar + ar2

array([[ 5,  7,  9],
       [ 4, 17,  9],
       [16,  1,  1]])

In [81]:
ar * ar2

array([[ 4, 10, 18],
       [ 0, 60, 18],
       [63,  0,  0]])

In [82]:
[1,2,4] + [2, 5, 6]

[1, 2, 4, 2, 5, 6]

In [84]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [85]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [86]:
type(np.where(ar>5))

tuple

In [87]:
np.count_nonzero(ar)

8

In [88]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [89]:
ar[1,1] = 0

In [90]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 2, 0, 1], dtype=int64))

In [91]:
import sys

In [92]:
py_arr = [2,3,4,5]

In [93]:
numpy_arr = np.array([2,3,4,5])

In [95]:
sys.getsizeof(1) * len(py_arr)

112

In [97]:
numpy_arr.itemsize * numpy_arr.size

16